const ADMIN = "admin";
const USER = "user";

export const Api = {
  Admin: {
    Auth: {
      LOGIN: `${ADMIN}/login`,
      CHANGE_PASSWORD: `${ADMIN}/change-password`,
      UPDATE_PROFILE: `${ADMIN}/edit-profile`,
      FORGOT_PASSWORD: `${ADMIN}/forgot-password`,
      VERIFY_OTP: `${ADMIN}/verify-otp`,
      RESET_PASSWORD: `${ADMIN}/reset-password`,
      ADMIN_LOGIN_WITH_OTP: `${ADMIN}/admin-login-by-otp`,
      RESEND_OTP: `${ADMIN}/resend-otp`,
      LOGIN_VERIFY_OTP: `${ADMIN}/login-verify-otp`,
      RESEND_FORGOT_PASSWORD_OTP: `${ADMIN}/resend-forgot-password-otp`,
    },
    InternshipCourse: {
      GET_INTERNSHIP_COURSES: `${ADMIN}/get-internship`,
      ADD_EDIT_COURSE: `${ADMIN}/add-edit-internship`,
      DELETE_COURSE: `${ADMIN}/delete-internship`,
      GET_SINGLE_INTERNSHIP: `${ADMIN}/get-single-internship`,
      ADD_EDIT_WEEKWISE_MANAGEMENT: `${ADMIN}/add-edit-week-managment`,
      GET_WEEK: `${ADMIN}/get-week`,
      GET_SINGLE_WEEK: `${ADMIN}/get-single-week`,
      DELETE_WEEK: `${ADMIN}/delete-week`,
    },
    Course: {
      GET_COURSES: `${ADMIN}/get-courses`,
      ADD_COURSE: `${ADMIN}/add-course`,
      DELETE_COURSE: `${ADMIN}/delete-course`,
      STUDENT_COURSES: `${ADMIN}/get-student-courses`,
      STUDENT_INTERNSHIPS: `${ADMIN}/get-student-internships`,
    },
    Hackathon: {
      GET_ALL_COURSES: `${ADMIN}/get-course-list`,
      ADD_EDIT_HACKATHON: `${ADMIN}/add-edit-hackathon`,
      DELETE_HACKATHON: `${ADMIN}/delete-hackathon`,
      GET_ALL_HACKATHON: `${ADMIN}/get-all-hackathon`,
      GET_HACKATHON_BY_ID: `${ADMIN}/get-single-hackathon`,
      GET_HACKATHON_LIST: `${ADMIN}/get-hackathon-list`,
    },
    FAQ: {
      GET_ALL_FAQ: `${ADMIN}/get-all-faqs`,
      ADD_EDIT_FAQ: `${ADMIN}/add-edit-faq`,
      DELETE_FAQ: `${ADMIN}/delete-faq`,
      GET_FAQ_BY_ID: `${ADMIN}/get-faq-by-id`,
    },
    TESTIMONIAL: {
      GET_ALL_TESTIMONIAL: `${ADMIN}/get-all-testimonials`,
      ADD_EDIT_TESTIMONIAL: `${ADMIN}/add-edit-testimonial`,
      DELETE_TESTIMONIAL: `${ADMIN}/delete-testimonial`,
      GET_TESTIMONIAL_BY_ID: `${ADMIN}/get-testimonial-by-id`,
    },
    Sections: {
      GET_SECTIONS: `${ADMIN}/get-section`,
      ADD_SECTIONS: `${ADMIN}/add-section`,
      DELETE_SECTIONS: `${ADMIN}/delete-section`,
      GET_SINGLE_SECTION: `${ADMIN}/get-single-section`,
    },
    Topic: {
      ADD_TOPIC: `${ADMIN}/add-topic`,
      DELETE_TOPIC: `${ADMIN}/delete-topic`,
      CHANGE_TOPIC_STATUS: `${ADMIN}/change-topic-status`,
      GET_TOPIC: `${ADMIN}/get-topic`,
      GET_TOPIC_BY_ID: `${ADMIN}/get-topic-by-id`,
      GET_TOPICS_BY_SECTION: `${ADMIN}/get-topics-by-section-id`,
    },
    QUIZ: {
      GET_ALL_QUIZ: `${ADMIN}/get-all-quiz`,
      GET_QUIZ_BY_ID: `${ADMIN}/get-quiz-by-id`,
      ADD_EDIT_QUIZ: `${ADMIN}/add-edit-quiz`,
      UPDATE_QUIZ_STATUS: `${ADMIN}/update-quiz-status`,
      DELETE_QUIZ: `${ADMIN}/delete-quiz`,
      GET_ALL_QUIZ_RESULT: `${ADMIN}/get-all-quiz-result`,
      GET_QUIZ_RESULT_BY_ID: `${ADMIN}/get-quiz-result`,
    },
    TEAM: {
      GET_TEAM_LIST: `${ADMIN}/get-all-team`,
      GET_TEAN_DETAIL: `${ADMIN}/get-team-by-id`,
      ADD_TEAM_FEEDBACK: `${ADMIN}/add-team-feedback`,
      EXPORT_TEAM_LIST: `${ADMIN}/export-all-team`,
      DELETE_TEAM_MEMBER: `${ADMIN}/delete-team-member-by-id`,
      DELETE_TEAM: `${ADMIN}/delete-team-by-id`,
      UPDATE_ADMIN_TEAM: `${ADMIN}/edit-team`,
    },
    PWD: {
      GET_FEEDBACK_LIST: `${ADMIN}/get-pwd-feedbacks`,
      GET_PWD_FEEDBACK: `${ADMIN}/get-single-feedback`,
    },
    GET_CONTACT_QUERY_LIST: `${ADMIN}/get-contact-us-list`,
    GET_CONTACT_QUERY_BY_ID: `${ADMIN}/get-contact-us`,
    REPLY_TO_CONTACT_INQUIRY: `${ADMIN}/reply-contact-inquiry`,
    GET_COURSE_TRACKING: `${ADMIN}/get-course-tracking`,
    GET_COURSE_RATING: `${ADMIN}/get-course-rating`,
    GET_COURSE_RATING_BY_ID: `${ADMIN}/get-course-rating`,
    GET_ALL_INTERNSHIPS: `${ADMIN}/get-all-internships`,
    Dashboard: {
      GET_DASHBOARD_DATA: `${ADMIN}/get-registerd-user-count`,
      GET_STUDENT_CHART_DATA: `${ADMIN}/get-student-registered-graph`,
      GET_INTERNSHIP_CHART_DATA: `${ADMIN}/get-internship-registered-graph`,
      GET_INTERNSHIP_REGISTER_USER_COUNT: `${ADMIN}/get-internship-register-user-count`,
    },
    Internship: {
      COURSE_TRACKING_LIST: `${ADMIN}/get-internship-course-tracking`,
      WEEK_TRACKING_LIST: `${ADMIN}/get-internship-week-tracking`,
      GET_ALL_INTERNSHIP: `${ADMIN}/get-internship-list`,
      GET_ALL_INTERNSHIP_WEEk: `${ADMIN}/get-all-internship-week`,
      CHANGE_STUDENT_INTERNSHIP: `${ADMIN}/change-student-internship`,
    },
    INTERNSHIP_QUIZ: {
      GET_ALL_INTERNSHIP_QUIZ_RESULT: `${ADMIN}/get-internship-quiz-result`,
      GET_INTERNSHIP_QUIZ_RESULT_BY_ID: `${ADMIN}/get-internship-quiz-result`,
    },
    ASSESSMENT_LIST: {
      GET_SINGLE_ASSESSMENT: `${ADMIN}/get-single-assessment`,
    },
    User: {
      CHECK_CERTIFICATE: `${USER}/check-certificate`,
      COURSE_CERTIFICATE: `${USER}/download-course-certificate`,
      INETERSHIP_CERTIFICATE: `${USER}/download-internship-certificate`,
      GET_INTERNSHIP_QUIZ_RESULT: `${USER}/get-internship-quiz-result`,
      INTERNSHIP_QUIZ_SUBMIT: `${USER}/internship-quiz-submission`,
      GET_SINGLE_INTERNSHIP_COURSE: `${USER}/get-internship-course-by-id`,
      ADD_INTERNSHIP_PDF_TRACKING: `${USER}/add-pdf-internship-course-tracking`,
      INTERNSHIP_TOPIC_DETAIL: `${USER}/get-topic-course-by`,
      INTERNSHIP_TOPIC_TRACKING: `${USER}/add-internship-tracking`,
      GET_INTERNSHIP_WEEK_TRACKING: `${USER}/get-week-tracking`,
      GET_SINGLE_WEEK: `${USER}/get-single-week`,
      UPLOAD_INTERNSHIP_WEEK_ASSIGNMENT: `${USER}/upload-assesment`,
      GET_SINGLE_INTERNSHIP: `${USER}/get-single-internship`,
      GET_ALL_INTERNSHIP_COURSES: `${USER}/get-internship-list`,
      FETCH_LIST: `${ADMIN}/users`,
      FETCH_SINGLE_USER: `${ADMIN}/users`,
      USER_ACTIVE_DEACTIVE: `${ADMIN}/user-active-deactive`,
      DELETE_USER: `${ADMIN}/user-delete`,
      ADD_USER: `${ADMIN}/add-user`,
      UPDATE_USER: `${ADMIN}/update-user`,
      USER_REGISTER_API: `${USER}/register`,
      ALL_DISTRICT_API: `${USER}/get-district`,
      GET_SINGLE_USER_API: `${USER}/get-user-profile`,
      ALL_TALUKA_API: `${USER}/get-taluka`,
      ALL_COLLEGE_API: `${USER}/get-college`,
      USER_VERIFY_OTP_API: `${USER}/verify-otp`,
      LOGIN: `${USER}/login`,
      CHANGE_PASSWORD: `${USER}/change-password`,
      UPDATE_PROFILE: `${USER}/profile-update`,
      FORGOT_PASSWORD: `${USER}/forgot-password`,
      VERIFY_OTP: `${USER}/otp-verify`,
      RESET_PASSWORD: `${USER}/reset-password`,
      USER_LOGIN_WITH_OTP: `${USER}/user-login-by-otp`,
      RESEND_OTP: `${USER}/resend-otp`,
      GET_LATEST_COURSES: `${USER}/get-latest-course`,
      GET_SINGLE_COURSE: `${USER}/get-course-by-id`,
      GET_SINGLE_TOPIC: `${USER}/get-course-by-topic`,
      ADD_CONTACT_US: `${USER}/addContact`,
      ADD_VIDEO_TRACKING: `${USER}/add-video-tracking`,
      ADD_PDF_TRACKING: `${USER}/add-pdf-tracking`,
      GET_VIDEO_TRACKING: `${USER}/get-video-tracking`,
      CONTINUE_WATCHING: `${USER}/continue-watching`,
      FETCH_QUIZ_BY_COURSE_ID: `${USER}/get-quiz`,
      SUBMIT_QUIZ: `${USER}/quiz-submission`,
      GET_LATEST_HACKATHON: `${USER}/get-hackathon`,
      GET_QUIZ_RESULT: `${USER}/get-quiz-result`,
      GET_PASSED_QUIZ_RESULT: `${USER}/get-passed-results`,
      DOWNLOAD_CERTIFICATE: `${USER}/download-quiz-certificate`,
      GET_CREATE_TEAM_ELIGBLE: `${USER}/check-create-team`,
      GET_USER_EMAIL_AND_ID: `${USER}/get-user`,
      CREATE_TEAM: `${USER}/create-team`,
      INVITE_MEMBER: `${USER}/invite-members`,
      GET_HACKATHON_TEAM_INVITATION: `${USER}/get-hackathon-team-invitation`,
      GET_HACKATHON_INVITATION: `${USER}/get-hackathon-invitation`,
      HACKATHON_INVITATION_STATUS: `${USER}/hackathon-invitation-status`,
      GET_TEAM_BY_USER: `${USER}/get-my-team`,
      GET_TEAM_BY_ID: `${USER}/get-team`,
      GET_TEAM_BY_HACKATHON: `${USER}/get-team-by-hackathon`,
      DELETE_TEAM_BY_HACKATHON: `${USER}/delete-team-by-hackathon`,
      GET_ALL_FAQ: `${USER}/get-all-faqs`,
      ADD_PWD_FEEDBACK: `${USER}/add-pwd-feedback`,
      GET_ALL_TESTIMONIAL: `${USER}/get-all-testimonials`,
      GET_TESTIMONIAL_BY_ID: `${USER}/get-testimonial-by-id`,
      ADD_COURSE_RATING: `${USER}/course-rating`,
      GET_TEAM_LIST: `${USER}/get-all-team`,
      GET_TEAN_DETAIL: `${USER}/get-team-by-id`,
      ADD_TEAM_DOCUMENT: `${USER}/upload-team-documents`,
      GET_TEAM_DOCUMENT: `${USER}/get-team-documents`,
      GET_USER_NOTIFICATIONS: `${USER}/get-user-notifications`,
      GET_USER_UNREAD_NOTIFICATIONS: `${USER}/get-user-unread-notifications`,
      APPLY_FOR_INTERNSHIP: `${USER}/apply-for-internship`,
      CHECK_INTERNSHIP_APPLICATION: `${USER}/internship-application`,
      MY_COURSES: `${USER}/get-my-courses`,
      MY_INTERNSHIPS: `${USER}/get-my-internships`,
      GET_FEEDBACK: `${USER}/get-feed-back`,
      IMPORT_BULK_STUDENTS: `${ADMIN}/import-bulk-students`,
      ALL_STREAMS: `${USER}/get-streams`,
      ALL_SEMESTERS: `${USER}/get-semesters`,
    },
    ASSESSMENT: {
      GET_ASSESSMENT_LIST: `${ADMIN}/assesment-list`,
      UPDATE_ASSESMENT: `${ADMIN}/update-feedback-assessment`,
    },
  },
};
